{% set name = "pytest-asyncio-cooperative" %}
{% set version = "0.37.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c7d8823c638374420c9b7e55caa345527153c76e0c458ac9416df4b039705e6b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - pytest

test:
  imports:
    - pytest_asyncio_cooperative
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pytest-asyncio-cooperative/
  summary: Run all your asynchronous tests cooperatively.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
